apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dikshat1024/backend:latest

          ports:
            - containerPort: 5000

          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/cafe