version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ..
      dockerfile: Docker/backend.Dockerfile   # ✅ FIXED
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cafe
    depends_on:
      - mongo

  frontend:
    build:
      context: ..
      dockerfile: Docker/frontend.Dockerfile  # ✅ FIXED
    ports:
      - "3000:80"
    depends_on:
      - backend